max_width = 80
format_strings = true
wrap_comments = true
normalize_comments = true
fn_single_line = true
where_single_line = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true
reorder_modules = true
match_block_trailing_comma = true
use_try_shorthand = true
use_field_init_shorthand = true
error_on_unformatted = true
